# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_beaver age1j6naf8x20slpur7awgnjhc5vdjerzn5psqe94gdtxn5wrwvw7ssstdvnhp
  # - &admin_otter 
creation_rules:
  - path_regex: .*\.sops\.beaver\.(yaml|json|env|ini|[^.]*\.bin)$
    key_groups:
      - age:
        - *admin_beaver

  - path_regex: .*\.sops\.homelab\.(yaml|json|env|ini|[^.]*\.bin)$
    key_groups:
      - age:
        - *admin_beaver
        # - *admin_otter
