# SPDX-FileCopyrightText: 2025 FreshlyBakedCake
# SPDX-FileCopyrightText: 2022 Markus Dobel
#
# SPDX-License-Identifier: MIT

# Inspired by:
# https://github.com/FreshlyBakedCake/PacketMix/blob/36990eb658ab4c6c3efa0aaa606dacf3dec285c1/.github/workflows/nixos.yml

name: Build nix derivations and push to cachix

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease
        with:
          extra_nix_config: "experimental-features = nix-command"

      - run: cd $GITHUB_WORKSPACE

      - name: Setup Cachix Cache
        uses: cachix/cachix-action@v16
        with:
          name: "beaver-lodge"
          authToken: "${{ secrets.CACHIX_TOKEN }}"

      # see https://git.lix.systems/lix-project/lix/issues/545
      - name: Fix apparmor configuration for building Lix
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Build all systems
        run: nix build -f ./nilla.nix packages.allNixOSSystems.result.x86_64-linux --show-trace

      - if: github.event_name == 'push'
        name: Push to release branch
        run: |
          git push -f origin HEAD:release
